---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: sanketp29
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "sanketp29/spe-mini-project"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
        
    - name: Create Docker container
      shell: docker create --name scientific-calculator -it sanketp29/spe-mini-project
      register: docker_create_result
      
    - name: Display Docker Create Result
      debug:
        var: docker_create_result

    - name: Start created Docker container
      shell: docker start scientific-calculator
